### ISSUE TITLE
Ruby docs incomplete

### ISSUE THREAD

**Issue by henrik** [paypal/Checkout-Ruby-SDK#15]
Hi,

Please see https://twitter.com/henrik/status/1122200659594567681.

Twitter support passed me on to Merchant Technical Support which said to tell you here…

**Comment by rajarampadmanathan** [comment]
Thanks @henrik for contacting us. Will look into it and get back to you.

**Comment by rajarampadmanathan** [comment]
@henrik - I looked into the sample and the sample returns the response which has order id.
`Samples::CaptureIntentExamples::CreateOrder::new::create_order(true).result.id` should return order id. 

Looks like debugs statements (Ex. puts "Order ID: #" instead of puts "Order ID: #{response.result.id}") are truncated in the docs. I will ask team to look into it.

**Comment by henrik** [comment]
Hi @rajarampadmanathan, thank you! Yup, I did eventually get it working, by looking at the Node JS example to see what the server-side was actually supposed to return :) So would be great if the Ruby code example showed the full server side code.
